export const container: string;
export const downloadFrom: string;
export const elements: string;
export const footerButtons: string;
export const footerLogo: string;
export const items: string;
export const logo: string;
export const logoElement: string;
export const logoText: string;
