export const btnCategories: string;
export const dropdownMenuCat: string;
export const dropdownMenuSub: string;
export const menu: string;
export const menuContainer: string;
export const menuItemCat: string;
export const menuItemSub: string;
export const mymove: string;
export const mymoves: string;
